[package]
name = "example"
version = "0.1.0"
edition = "2021"


[dependencies]
backend = {path = "../backend"}
dotenv = "0.15.0"
rocket = "0.5.0"
rocket_cors = "0.6.0"
rocket_db_pools = { version = "0.1.0", features = ["mongodb"] }
